# https://starship.rs/ja-jp/config/
"$schema" = 'https://starship.rs/config-schema.json'

# ã‚·ã‚§ãƒ«ãƒ—ãƒ­ãƒ³ãƒ—ãƒˆã®é–“ã«ç©ºè¡Œã‚’è¿½åŠ ã—ã¾ã™
add_newline = true

# ã‚¿ã‚¤ãƒ ã‚¢ã‚¦ãƒˆæ™‚é–“
scan_timeout = 420

# ã‚³ãƒãƒ³ãƒ‰ã‚¿ã‚¤ãƒ ã‚¢ã‚¦ãƒˆ
command_timeout = 4422

# ã‚«ãƒ©ãƒ¼ãƒ‘ãƒ¬ãƒƒãƒˆã®å®šç¾©
palette = 'color'

# ç¶™ç¶šãƒ—ãƒ­ãƒ³ãƒ—ãƒˆã®è¡¨ç¤º
# continuation_prompt = "â–¶â–¶"

# ä¸¦ã³é †
format = """
[ï‚› ](gray)\
[â–‘â–’â–“](gray)\
$os\
$username\
$hostname\
[î‚´](fg:gray bg:navy)\
$directory\
[î‚´](fg:navy bg:dark)\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
[î‚´](fg:dark bg:dd)\
$fill\
$nodejs\
$rust\
$golang\
$php\
$java\
$python\
$ruby\
$bun\
$package\
[î‚´](fg:dd bg:ddd)\
$time\
$battery\
$memory_usage\
[î‚´](fg:ddd bg:ddd)\
$cmd_duration\
[î‚´](fg:ddd)\
$line_break\
$character\
$localip\
$docker_context\
$custom\
$shell\
"""

# right_format = """
# $cmd_duration
# $time
# """

# è‰²ã®è¨­å®š
[palettes.color]
gray = '#a0a9cb'
white = '#e3e5e5'
navy = '#769ff0'
dark = '#393260'
dd = '#212736'
ddd = '#1d2230'

[os]
disabled = false
style = "fg:navy bg:gray"

[os.symbols]
Windows = "î˜ª "
Ubuntu = "ïŒ› "
Linux = "ïŒš "
Macos = "îœ‘ "
Raspbian = "ïŒ• "
RedHatEnterprise = "ïŒ– "

# ãƒ¦ãƒ¼ã‚¶ãƒ¼å
[username]
style_user = "fg:navy bg:gray"
style_root = "fg:red bg:gray"
format = '[($user)@]($style bold)'
disabled = false
show_always = true

# ãƒ›ã‚¹ãƒˆå
[hostname]
ssh_only = false
style = "fg:navy bg:gray"
format = '[$ssh_symbol$hostname:]($style bold)'
disabled = false

[directory]
style = "fg:white bg:navy"
format = "[ï„• $path]($style bold)"
truncate_to_repo = false
truncation_length = 5
truncation_symbol = "â€¦/"

[directory.substitutions]
"Documents" = "ïœ˜ "
"Downloads" = "ï€™  "
"Music" = "ï€  "
"Pictures" = "ï€¾  "

[git_branch]
symbol = "ï˜ "
style = "fg:navy bg:dark"
format = '[ $symbol $branch ]($style bold)'

[git_status]
style = "fg:navy bg:dark"
format = '[($all_status$ahead_behind)]($style bold)'
conflicted = "ğŸ’¥ "
ahead = "ğŸğŸ’¨ "
behind = "ğŸ˜° "
diverged = "ğŸ˜µ "
untracked = "ğŸŒš "
stashed = "ğŸ“¦ "
modified = "ğŸ“ "
staged = 'ğŸ”¦ '
renamed = "ğŸ· "
deleted = "ğŸ—‘ "

[nodejs]
symbol = "îœ˜ "
style = "fg:navy bg:dd"
format = '[ $symbol($version)]($style bold)'

[rust]
symbol = "î¨ "
style = "fg:navy bg:dd"
format = '[ $symbol($version)]($style bold)'

[golang]
symbol = "ï³‘ "
style = "fg:navy bg:dd"
format = '[ $symbol($version)]($style bold)'

[php]
symbol = "î˜ˆ "
style = "fg:navy bg:dd"
format = '[ $symbol($version)]($style bold)'

[java]
symbol = 'ğŸŒŸ '
style = "fg:navy bg:dd"
format = '[ $symbol($version)]($style bold)'

[python]
symbol = 'îˆµ '
style = "fg:navy bg:dd"
format = '[ $symbol($version)]($style bold)'

[ruby]
symbol = 'î¨ '
style = "fg:navy bg:dd"
format = '[ $symbol($version)]($style bold)'

[bun]
symbol = 'ğŸ '
style = "fg:navy bg:dd"
format = '[ $symbol($version)]($style bold)'

[package]
symbol = "ï£– "
style = "fg:navy bg:dd"
format = '[ $symbol($version)]($style bold)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:gray bg:ddd"
format = '[ïº $time]($style bold)'

# ãƒãƒƒãƒ†ãƒªãƒ¼è¡¨ç¤º
[battery]
full_symbol = 'ï‰€ '
charging_symbol = 'ï‡¦ '
discharging_symbol = 'âš ï¸ '
disabled = false
format = '[ $symbol$percentage]($style bold)'

# ãƒãƒƒãƒ†ãƒªãƒ¼ã‚’è¡¨ç¤ºã™ã‚‹ã‚¿ã‚¤ãƒŸãƒ³ã‚°ã€è¡¨ç¤ºã™ã‚‹éš›ã®æ–‡å­—ã®è‰²ã™ã‚‹éš›ã®æ–‡å­—ã®è‰²
[[battery.display]]
threshold = 101
style = "fg:gray bg:ddd"

[memory_usage]
disabled = false
threshold = -1
symbol = "ïˆ€ "
style = "fg:gray bg:ddd"
format = '[ $symbol${ram_pct}]($style bold)'

[cmd_duration]
style = "fg:navy bg:ddd"
min_time = 4200
format = '[$duration]($style bold)'

# IPã‚¢ãƒ‰ãƒ¬ã‚¹
[localip]
ssh_only = true
style = "fg:navy bg:gray"
format = '[@$localipv4]($style bold) '
disabled = false

[docker_context]
format = "[ğŸ‹$context](blue bold) "

[character]
success_symbol = "[â™¨ï¸ ](green bold)"
error_symbol = "[â™¨ï¸ ](red bold)"

[shell]
fish_indicator = 'ïœ¹ '
powershell_indicator = 'ï‘ _ '
style = 'green'
# format = '[$indicatorï…•](strikethrough red bold)ï‰… [kush]($style bold) [ï…š](yellow bold) '
format = '[$indicator](green bold) [ï…š](yellow bold) '
#format = '[$indicator\$]($style bold) '
disabled = false

# x86 or arm64
[custom.arch]
command = "uname -m"
when = """ test $(uname -m) = "x86_64" """
style = "bold navy"
format = "[ $output]($style bold)"

[gcloud]
disabled = true
